version: '3.9'
services:
  mssql:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: cop
      MARIADB_USER: juliano
      MARIADB_PASSWORD: 123456
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
volumes:
  mariadb_volume:
