CREATE TABLE Customers(
  Id VARCHAR(36) PRIMARY KEY,
  Name VARCHAR(60) NOT NULL,
  Email VARCHAR(60) UNIQUE NOT NULL,
  Created DATETIME DEFAULT CURRENT_TIMESTAMP,
  Updated DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE Items(
  Id VARCHAR(36) PRIMARY KEY,
  Name VARCHAR(60) UNIQUE NOT NULL,
  Price FLOAT NOT NULL,
  Created DATETIME DEFAULT CURRENT_TIMESTAMP,
  Updated DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE Orders(
  Id VARCHAR(36) PRIMARY KEY,
  CustomerId VARCHAR(36) NOT NULL,
  FOREIGN KEY (CustomerId)
  REFERENCES Customers(Id),
  Total FLOAT NOT NULL,
  Created DATETIME DEFAULT CURRENT_TIMESTAMP,
  Updated DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE OrderItems(
  OrderId VARCHAR(36) NOT NULL,
  FOREIGN KEY (OrderId)
  REFERENCES Orders(Id),
  ItemId VARCHAR(36) NOT NULL,
  FOREIGN KEY (ItemId)
  REFERENCES Items(Id),
  Quantity INT NOT NULL,
  Created DATETIME DEFAULT CURRENT_TIMESTAMP,
  Updated DATETIME DEFAULT CURRENT_TIMESTAMP
)

INSERT INTO Customers(Id, Name, Email)
VALUES('06307706-45ce-468e-807d-36d4e7ae8d98', 'Juliano', 'juliano@test.com')

INSERT INTO Items(Id, Name, Price)
VALUES('ccf0338f-9e44-4795-89f0-685da50ca17a', 'Teclado Mecânico Gamer HyperX Mars RGB', 330),
('f8193f5a-99c6-4001-8c77-0ddcdd881c65', 'Notebook asus vivobook', 3700)
